---
# This workflow will install Python dependencies and run tests
# across operating systems, select versions of Python, and user + dev environments
# For more info see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python 🐍 CI/CD tests

on:
  push:
    branches: [main, develop]
    paths-ignore: # prevents workflow execution when only these types of files are modified
      - "**.md" # wildcards prevent file in any repo dir from trigering workflow
      - "**.bib"
      - "LICENSE"
      - ".gitignore"
  pull_request:
    branches: [main, develop]
    paths-ignore:
      - "**.md"
      - "**.bib"
      - "LICENSE"
      - ".gitignore"
  workflow_dispatch: # also allow manual trigger, for testing purposes

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        py-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv and Python ${{ matrix.py-version }}
        uses: astral-sh/setup-uv@v10
        with:
          python-version: ${{ matrix.py-version }}
          enable-cache: true

      - name: Test with pytest
        run: uv run --locked --no-default-groups --group test pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
